import { ContendersData } from "./contendersData";

// TODO Change the contenderId from a String to a number
export const BetData = [
  {
    sport: "Featured",
    href: "featured",
    icon: "featured",
    alternateIcon: "featuredAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/512/1828/1828884.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/512/1828/1828884.png",
    availableBets: [
      {
        type: "outright",
        title: "2022-23 NBA Championship Winner",
        contendersData: [
            {contenderId: "bostonceltics", buttonId:93452},
            {contenderId: "miamiheat", buttonId:9043930},
            {contenderId: "goldenstatewarriors", buttonId:904390921},
            {contenderId: "dallasmavericks", buttonId:433432},
            {contenderId: "detroitpistons", buttonId:906564390921},
            {contenderId: "memphisgrizzlies", buttonId:9084390921},
            {contenderId: "chicagobulls", buttonId:2345},
            {contenderId: "brooklynnets", buttonId:9043903523921},
            {contenderId: "atlantahawks", buttonId:654},
            {contenderId: "neworleanspelicans", buttonId:123},
            {contenderId: "orlandomagic", buttonId:456},
            {contenderId: "philadelphia76ers", buttonId:6543},
            {contenderId: "denvernuggets", buttonId:3265},
            {contenderId: "torontoraptors", buttonId:65432},
            {contenderId: "newyorkknicks", buttonId:236},
            {contenderId: "clevelandcavaliers", buttonId:8492},
            {contenderId: "charlottehornets", buttonId:43534},
            {contenderId: "portlandtrailblazers", buttonId:52345},
            {contenderId: "washingtonwizards", buttonId:126437},
            {contenderId: "utahjazz", buttonId:654325},
            {contenderId: "sacramentokings", buttonId:7583},
            {contenderId: "oklahomacitythunder", buttonId:62049},
            {contenderId: "indianapacers", buttonId:2346626},
            {contenderId: "phoenixsunds", buttonId:236266622},
            {contenderId: "houstonrockets", buttonId:544},
            {contenderId: "sanantoniospurs", buttonId:999333},
            {contenderId: "losangelesclippers", buttonId:2932552},
            {contenderId: "milwaukeebucks", buttonId:6653246},
            {contenderId: "minnesotatimberwolves", buttonId:9889028}
        ],
      },
      {
        type: "game",
        title: "Cincinnati Reds @ Philadelphia Phillies",
        contender1Data: {
          contenderId: "cincinnatireds",
          spread: "-1.5",
          spreadButtonId: 42663243,
          money: "-350",
          moneyButtonId: 42663244,
          total: "O 6.5",
          totalButtonId: 42663245,
        },
        contender2Data: {
          contenderId: "philadelphiaphillies",
          spread: "+1",
          spreadButtonId: 42663246,
          money: "+250",
          moneyButtonId: 42663247,
          total: "U 6.5",
          totalButtonId: 42663248,
        },
      },
      {
        type: "outright",
        title: "2022-23 WNBA Championship Winner",
        contendersData: [
            {contenderId: "chicagosky", buttonId:9934322},
            {contenderId: "minnesotalynx", buttonId:8237},
            {contenderId: "washingtonmystics", buttonId:89012},
            {contenderId: "seattlestorm", buttonId:489242},
            {contenderId: "losangelessparks", buttonId:73529},
            {contenderId: "phoenixmercury", buttonId:66936},
            {contenderId: "dallaswings", buttonId:552431},
            {contenderId: "connecticutsun", buttonId:903656},
            {contenderId: "chicagosky", buttonId:994322}
        ]
      },
      {
        type: "game",
        title: "Atlanta Braves @ Pittsburgh Pirates",
        contender1Data: {
          contenderId: "atlantabraves",
          spread: "-5",
          spreadButtonId: 2930423,
          money: "-600",
          moneyButtonId: 23409234,
          total: "O 8.5",
          totalButtonId: 90234234,
        },
        contender2Data: {
          contenderId: "pittsburghpirates",
          spread: "+5.5",
          spreadButtonId: 203094,
          money: "+300",
          moneyButtonId: 393242,
          total: "U 8.5",
          totalButtonId: 99323444,
        },
      },
    ],
  },
  {
    
    sport: "Basketball",
    href: "basketball",
    icon: "basketball",
    alternateIcon: "basketballAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/512/921/921183.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/512/921/921183.png",
    availableBets: [
      {
        type: "outright",
        title: "2022-23 NBA Championship Winner",
        contendersData: [
            {contenderId: "bostonceltics", buttonId:93452},
            {contenderId: "miamiheat", buttonId:9043930},
            {contenderId: "goldenstatewarriors", buttonId:904390921},
            {contenderId: "dallasmavericks", buttonId:433432},
            {contenderId: "detroitpistons", buttonId:906564390921},
            {contenderId: "memphisgrizzlies", buttonId:9084390921},
            {contenderId: "chicagobulls", buttonId:2345},
            {contenderId: "brooklynnets", buttonId:9043903523921},
            {contenderId: "atlantahawks", buttonId:654},
            {contenderId: "neworleanspelicans", buttonId:123},
            {contenderId: "orlandomagic", buttonId:456},
            {contenderId: "philadelphia76ers", buttonId:6543},
            {contenderId: "denvernuggets", buttonId:3265},
            {contenderId: "torontoraptors", buttonId:65432},
            {contenderId: "newyorkknicks", buttonId:236},
            {contenderId: "clevelandcavaliers", buttonId:8492},
            {contenderId: "charlottehornets", buttonId:43534},
            {contenderId: "portlandtrailblazers", buttonId:52345},
            {contenderId: "washingtonwizards", buttonId:126437},
            {contenderId: "utahjazz", buttonId:654325},
            {contenderId: "sacramentokings", buttonId:7583},
            {contenderId: "oklahomacitythunder", buttonId:62049},
            {contenderId: "indianapacers", buttonId:2346626},
            {contenderId: "phoenixsunds", buttonId:236266622},
            {contenderId: "houstonrockets", buttonId:544},
            {contenderId: "sanantoniospurs", buttonId:999333},
            {contenderId: "losangelesclippers", buttonId:2932552},
            {contenderId: "milwaukeebucks", buttonId:6653246},
            {contenderId: "minnesotatimberwolves", buttonId:9889028}
        ],
      },
      {
        type: "outright",
        title: "2022-23 WNBA Championship Winner",
        contendersData: [
            {contenderId: "chicagosky", buttonId:9934322},
            {contenderId: "minnesotalynx", buttonId:8237},
            {contenderId: "washingtonmystics", buttonId:89012},
            {contenderId: "seattlestorm", buttonId:489242},
            {contenderId: "losangelessparks", buttonId:73529},
            {contenderId: "phoenixmercury", buttonId:66936},
            {contenderId: "dallaswings", buttonId:552431},
            {contenderId: "connecticutsun", buttonId:903656},
            {contenderId: "chicagosky", buttonId:994322}
        ]
      },
      {
        type: "game",
        title: "Milwaukee Bucks @ Minnesota Timberwolves",
        contender1Data: {
          contenderId: "milwaukeebucks",
          spread: "+7.5",
          spreadButtonId: 93940,
          money: "+140",
          moneyButtonId: 3452,
          total: "O 160",
          totalButtonId: 129438,
        },
        contender2Data: {
          contenderId: "minnesotatimberwolves",
          spread: "-7",
          spreadButtonId: 637326,
          money: "-120",
          moneyButtonId: 33322,
          total: "U 160",
          totalButtonId: 777847,
        },
      },
      {
        type: "game",
        title: "Chicago Sky @ Minnesota Lynx",
        contender1Data: {
          contenderId: "chicagosky",
          spread: "+6.5",
          spreadButtonId: 756837,
          money: "+140",
          moneyButtonId: 15409,
          total: "O 160",
          totalButtonId: 893654,
        },
        contender2Data: {
          contenderId: "minnesotalynx",
          spread: "-7",
          spreadButtonId: 628578,
          money: "-120",
          moneyButtonId: 48395,
          total: "U 160",
          totalButtonId: 958473,
        },
      },
    ],
  },
  {
    sport: "Baseball",
    href: "baseball",
    icon: "baseball",
    alternateIcon: "baseballAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/512/3371/3371359.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/512/3371/3371359.png",
    availableBets: [
      {
        type: "game",
        title: "Chicago Cubs @ Seattle Mariners",
        contender1Data: {
          contenderId: "chicagocubs",
          spread: "-2.5",
          spreadButtonId: 422223551,
          money: "-160",
          moneyButtonId: 422223552,
          total: "O 16",
          totalButtonId: 422223553,
        },
        contender2Data: {
          contenderId: "seattlemariners",
          spread: "+2",
          spreadButtonId: 422223554,
          money: "+180",
          moneyButtonId: 422223555,
          total: "U 16",
          totalButtonId: 422223556,
        },
      },
      {
        type: "game",
        title: "Cincinnati Reds @ Philadelphia Phillies",
        contender1Data: {
          contenderId: "cincinnatireds",
          spread: "-1.5",
          spreadButtonId: 42663243,
          money: "-350",
          moneyButtonId: 42663244,
          total: "O 6.5",
          totalButtonId: 42663245,
        },
        contender2Data: {
          contenderId: "philadelphiaphillies",
          spread: "+1",
          spreadButtonId: 42663246,
          money: "+250",
          moneyButtonId: 42663247,
          total: "U 6.5",
          totalButtonId: 42663248,
        },
      },
      {
        type: "game",
        title: "Atlanta Braves @ Pittsburgh Pirates",
        contender1Data: {
          contenderId: "atlantabraves",
          spread: "-5",
          spreadButtonId: 2930423,
          money: "-600",
          moneyButtonId: 23409234,
          total: "O 8.5",
          totalButtonId: 90234234,
        },
        contender2Data: {
          contenderId: "pittsburghpirates",
          spread: "+5.5",
          spreadButtonId: 203094,
          money: "+300",
          moneyButtonId: 393242,
          total: "U 8.5",
          totalButtonId: 99323444,
        },
      },
    ],
  },
  {
    sport: "Soccer",
    href: "soccer",
    icon: "soccer",
    alternateIcon: "soccerAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/512/907/907690.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/512/907/907690.png",
    availableBets: [
      {
        type: "outright",
        title: "13 Contenders",
        contendersData: [
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
        ],
      },
      {
        type: "outright",
        title: "12 Contenders",
        contendersData: [
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
        ],
      },
      {
        type: "outright",
        title: "5 Contenders",
        contendersData: [
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
        ],
      },
      {
        type: "outright",
        title: "4 Contenders",
        contendersData: [
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
        ],
      },
      {
        type: "outright",
        title: "2 Contenders",
        contendersData: [
          {contenderId: "bostonceltics", buttonId:93452},
          {contenderId: "bostonceltics", buttonId:93452},
        ],
      },
    ],
  },
  {
    sport: "Football",
    href: "football",
    icon: "soccer",
    alternateIcon: "soccerAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/128/2087/2087177.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/128/2087/2087177.png",
    availableBets: []
  },
  {
    sport: "Boxing",
    href: "boxing",
    icon: "soccer",
    alternateIcon: "soccerAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/128/1804/1804582.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/128/1804/1804582.png",
    availableBets: []
  },
  {
    sport: "Bowling",
    href: "bowling",
    icon: "soccer",
    alternateIcon: "soccerAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/128/3390/3390440.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/128/3390/3390440.png",
    availableBets: []
  },
  {
    sport: "Rugby",
    href: "rugby",
    icon: "soccer",
    alternateIcon: "soccerAlternate",
    imageWhite: "https://cdn-icons-png.flaticon.com/128/902/902997.png",
    imageBlue: "https://cdn-icons-png.flaticon.com/128/902/902997.png",
    availableBets: []
  },
];
